### PR TITLE
www/room: basic game display techniques

### PR DESCRIPTION
**Pull request by j2kun**
This PR contains my partial progress on getting a room front-end set up. If you run `python app.py` and browse to `127.0.0.1:5000`, you will see the setup so far. It has a player hand centered at the bottom, and a trick centered in the page. I would like to merge this soon and then set up an issue for finishing it. What's left to do includes:

- [ ] Getting the other players "hands" to show up (face down) in their respective locations.
- [ ] Getting "I play a card" action to move a card from my hand to the bottom of the trick
- [ ] Getting "other player plays card" action to create a card at their respective location and move it to the center.
- [ ] Technical reorganization because I will want to do server-side javascript templating, instead of putting everything in `/static/`. This will require some more investigation on my part.
- [ ] Set up proper javascript testing framework.

Screenshot: 

screen shot 2017-02-12 at 5 26 30 pm

### CODE REVIEW

**Comment by j2kun** [comment]
@DanielNghiem Are you able to view the page in your development environment?

**Comment by DanielNghiem** [comment]
I am unable to connect to 127.0.0.1:5000, but this might be an issue with my machine.

**Comment by j2kun** [comment]
Are you still using cloud9? If so, try running changing [this line](https://github.com/j2kun/lonely-hearts/blob/master/app.py#L53) to 

```
app.run(host='0.0.0.0', port='8080')
```

Then run the server `python app.py`, and browse to `http://<workspacename>-<username>.c9users.io` and see if that renders. I'm looking at these two pages to figure this out:

 - https://docs.c9.io/docs/run-an-application
 - http://flask.pocoo.org/docs/0.12/api/#flask.Flask.run

**Comment by DanielNghiem** [comment]
Thanks! It work for me now.

**Pull request merged**
